import { Position } from "@ibozak23/kosarkaska-analitika";

export interface DemonstracijskiTim {
  readonly name: string;
  readonly city: string | null;
  readonly league: string;
  readonly season: string;
}

export interface DemonstracijskiIgrac {
  readonly jerseyNumber: number;
  readonly firstName: string;
  readonly lastName: string;
  readonly position: Position;
  readonly heightCm: number;
}

export interface DemonstracijskiSastav {
  readonly team: DemonstracijskiTim;
  readonly players: readonly DemonstracijskiIgrac[];
}

const IME_LIGE = "2. muška liga – sjever";
const SEZONA = "2025/2026";

function sastav(
  name: string,
  city: string | null,
  players: readonly DemonstracijskiIgrac[]
): DemonstracijskiSastav {
  return { team: { name, city, league: IME_LIGE, season: SEZONA }, players };
}

function igrac(
  jerseyNumber: number,
  firstName: string,
  lastName: string,
  position: Position,
  heightCm: number
): DemonstracijskiIgrac {
  return { jerseyNumber, firstName, lastName, position, heightCm };
}

export const LIGA: readonly DemonstracijskiSastav[] = [
  sastav("Grafičar", null, [
    igrac(4, "Bruno", "Bačani", Position.C, 202),
    igrac(5, "Filip", "Bačani", Position.PF, 202),
    igrac(6, "Matija", "Bačani", Position.PF, 200),
    igrac(7, "Leon", "Cifrek Rak", Position.SG, 191),
    igrac(8, "Filip", "Crnković", Position.C, 205),
    igrac(9, "Matej", "Jurčić", Position.C, 209),
    igrac(10, "Ante", "Kokolek", Position.SF, 195),
    igrac(11, "Bono", "Krušelj", Position.SG, 191),
    igrac(12, "Karlo", "Kuparić", Position.SF, 197),
    igrac(13, "Kai", "Novak", Position.SG, 189),
    igrac(14, "Marko", "Periša", Position.PG, 185),
    igrac(15, "Vito", "Periša", Position.SF, 195),
    igrac(17, "Roko", "Turek", Position.PG, 181),
    igrac(18, "Borna", "Vađunec", Position.SF, 198),
    igrac(19, "Luka", "Valdec", Position.SG, 193),
    igrac(20, "Matija", "Valdec", Position.PG, 180),
    igrac(21, "Luka", "Virag", Position.PG, 181),
    igrac(22, "Dominik", "Vrabec", Position.PF, 200),
    igrac(23, "Leon", "Žnidarić", Position.PF, 203),
  ]),
  sastav("Ivančica", "Ivanec", [
    igrac(4, "Petar", "Košćak", Position.PG, 184),
    igrac(5, "Martin", "Fištrek", Position.PG, 183),
    igrac(6, "Marko", "Bratković", Position.PF, 197),
    igrac(7, "Leonardo", "Matuza", Position.SG, 190),
    igrac(8, "Leon", "Sambora", Position.SG, 189),
    igrac(9, "Luka", "Putar", Position.SF, 196),
    igrac(10, "Ivan", "Božak", Position.SF, 194),
    igrac(11, "Stjepan", "Herceg", Position.PF, 201),
    igrac(12, "Marko", "Kapustić", Position.PF, 200),
    igrac(13, "Dario", "Livajić", Position.C, 205),
    igrac(14, "Luka", "Brlečić", Position.SG, 190),
    igrac(15, "Marko", "Bregović", Position.C, 203),
    igrac(17, "Bartol", "Canjuga", Position.SG, 186),
    igrac(18, "Mihael", "Cerovečki", Position.SF, 198),
    igrac(19, "Patrik", "Črnila", Position.SF, 196),
    igrac(20, "Martin", "Dukarić", Position.PG, 181),
    igrac(21, "Zenn", "Geček", Position.PF, 202),
    igrac(22, "Karlo", "Jakopović", Position.PG, 182),
    igrac(23, "Emanuel", "Ostoić", Position.C, 210),
    igrac(24, "Robert", "Sayemeldahr", Position.C, 207),
  ]),
  sastav("Koprivnica", "Koprivnica", [
    igrac(4, "Marko", "Brlečić", Position.C, 202),
    igrac(5, "Matija", "Gerić", Position.PG, 185),
    igrac(6, "Dorian", "Huzak", Position.PF, 204),
    igrac(7, "Dorian", "Jukić", Position.PF, 197),
    igrac(8, "Ivan", "Labazan", Position.SF, 198),
    igrac(9, "Leopold", "Ladan", Position.SG, 188),
    igrac(10, "Ivan", "Lisjak", Position.PF, 202),
    igrac(11, "Dorijan", "Lončarić", Position.SG, 191),
    igrac(12, "Roko", "Matijaško", Position.SF, 195),
    igrac(13, "Domagoj", "Mihoković", Position.SG, 187),
    igrac(14, "Robert", "Mihoković", Position.PG, 184),
    igrac(15, "Ivan", "Poznić", Position.SG, 188),
    igrac(17, "Luka", "Prepelić", Position.SF, 198),
    igrac(18, "Luka", "Rukavina", Position.PG, 181),
    igrac(19, "Martin", "Šadek", Position.PG, 181),
    igrac(20, "Andrija Božo", "Škarić", Position.PF, 197),
    igrac(21, "Andrija", "Švegović", Position.SF, 193),
    igrac(22, "Filip", "Tetec", Position.C, 201),
    igrac(23, "Bruno", "Tomašković", Position.SG, 189),
    igrac(24, "Nikola", "Tomašković", Position.PG, 187),
    igrac(25, "Luka", "Veljanovski", Position.C, 201),
    igrac(31, "Hrvoje", "Vrhovec", Position.C, 205),
  ]),
  sastav("Međimurje", null, [
    igrac(4, "Ante", "Božić", Position.SG, 192),
    igrac(5, "Noa", "Drvenkar", Position.PG, 182),
    igrac(6, "Vedran", "Gašparić", Position.C, 210),
    igrac(7, "Petar", "Glumac", Position.PG, 186),
    igrac(8, "Nikola", "Hren", Position.SG, 188),
    igrac(9, "Riko", "Karamatić", Position.SG, 187),
    igrac(10, "Edo", "Kraljić", Position.PG, 187),
    igrac(11, "Franjo", "Kranjčec", Position.SF, 194),
    igrac(12, "Mislav", "Kranjčec", Position.PF, 203),
    igrac(13, "Domagoj", "Kuzmić", Position.SF, 197),
    igrac(14, "Juraj", "Majnarić", Position.SF, 198),
    igrac(15, "Dorijan", "Majsan", Position.C, 203),
    igrac(17, "Franjo", "Palić", Position.C, 201),
    igrac(18, "Tin", "Pongrac", Position.PF, 203),
    igrac(19, "Niko", "Šarić", Position.PG, 187),
    igrac(20, "Matija", "Strbad", Position.SF, 197),
    igrac(21, "Patrik", "Tkalčec", Position.PF, 204),
    igrac(22, "Franko", "Zaspan", Position.SG, 191),
  ]),
  sastav("Mladost (Đ)", "Đurđevac", [
    igrac(4, "Mateo", "Balatinec", Position.PF, 203),
    igrac(5, "Vladimir", "Beljan", Position.PG, 181),
    igrac(6, "Petar", "Benotić", Position.C, 210),
    igrac(7, "Tomislav", "Benotić", Position.C, 209),
    igrac(8, "Luka", "Carek", Position.PG, 184),
    igrac(9, "Andrija", "Cestar", Position.PG, 180),
    igrac(10, "Leon", "Cestar", Position.PF, 202),
    igrac(11, "Karlo", "Čmrlec", Position.PF, 204),
    igrac(12, "Karlo", "Gašparić", Position.SG, 192),
    igrac(13, "Zoran", "Jančijev", Position.SG, 187),
    igrac(14, "Antun", "Marić", Position.SG, 191),
    igrac(15, "Igor", "Odobašić", Position.SG, 190),
    igrac(17, "Marko", "Osmokrović", Position.SF, 195),
    igrac(18, "Hrvoje", "Puljko", Position.PG, 180),
    igrac(19, "Roko", "Sedlar", Position.C, 204),
    igrac(20, "Branko", "Stojanov", Position.SF, 194),
    igrac(21, "Petar", "Sušanj", Position.SF, 197),
    igrac(22, "Luka", "Tišljar", Position.SF, 195),
    igrac(23, "Karlo", "Zovko", Position.PF, 202),
  ]),
  sastav("Petar Zrinski", null, [
    igrac(4, "Roko", "Balić", Position.PG, 185),
    igrac(5, "Tomislav", "Beljo", Position.PF, 203),
    igrac(6, "Luka", "Biondić", Position.SF, 194),
    igrac(7, "Filip", "Budimir", Position.C, 206),
    igrac(8, "Bruno", "Fašaić", Position.C, 203),
    igrac(9, "Damir", "Fašaić", Position.SF, 193),
    igrac(10, "Vito", "Gubijan", Position.C, 202),
    igrac(11, "Luka", "Horvat", Position.PG, 182),
    igrac(12, "Mario", "Kelava", Position.PF, 202),
    igrac(13, "Karlo", "Kelečić", Position.PG, 180),
    igrac(14, "Luka", "Klepec", Position.SG, 192),
    igrac(15, "Bojan", "Križanović", Position.PF, 204),
    igrac(17, "Vedran", "Mikac", Position.SG, 186),
    igrac(18, "Jakov", "Ninić", Position.SF, 197),
    igrac(19, "Ivan", "Perković", Position.SG, 186),
    igrac(20, "Kristijan", "Šamarija", Position.SF, 195),
    igrac(21, "Florijan", "Šašek", Position.PF, 197),
    igrac(22, "Luka", "Škaro", Position.C, 208),
    igrac(23, "Filip", "Tušek", Position.PG, 187),
    igrac(24, "Bruno", "Vrinjanin", Position.SG, 188),
  ]),
  sastav("Podravac", null, [
    igrac(4, "Viktor", "Cik", Position.PF, 198),
    igrac(5, "Patrik", "Fišer", Position.PG, 185),
    igrac(6, "Antun", "Gregar Hrženjak", Position.SF, 194),
    igrac(7, "Andrija", "Hrženjak", Position.C, 206),
    igrac(8, "Luka", "Jurički", Position.PF, 202),
    igrac(9, "Leonard", "Koščak", Position.SF, 196),
    igrac(10, "Antonio", "Kraljić", Position.PG, 183),
    igrac(11, "Bruno", "Križić", Position.SG, 193),
    igrac(12, "Nikola", "Laić", Position.SF, 194),
    igrac(13, "Mario", "Rajšić", Position.SG, 193),
    igrac(14, "Antonio", "Šoš", Position.PF, 204),
    igrac(15, "Lukas", "Šuvak", Position.C, 203),
    igrac(17, "Mihael", "Topolčić", Position.C, 205),
    igrac(18, "Luka", "Večenaj", Position.SG, 192),
    igrac(19, "Luka", "Žlender", Position.PG, 185),
  ]),
  sastav("Radnik", null, [
    igrac(4, "Matija", "Antolić", Position.SG, 191),
    igrac(5, "Jakov", "Beljo", Position.C, 209),
    igrac(6, "Roko", "Bolčić", Position.SG, 192),
    igrac(7, "Juraj", "Brkić", Position.PG, 182),
    igrac(8, "Patrik", "Cindrić", Position.SF, 196),
    igrac(9, "Petar", "Filipović", Position.PG, 186),
    igrac(10, "Luka", "Fržović", Position.SF, 199),
    igrac(11, "Jure", "Gunjina", Position.PG, 183),
    igrac(12, "Fabijan", "Gužvinec", Position.SF, 197),
    igrac(13, "Ivan", "Jelavić", Position.PF, 202),
    igrac(14, "Matija", "Kurpez", Position.PF, 201),
    igrac(15, "Filip", "Kuzel", Position.SG, 186),
    igrac(17, "Mario Stjepan", "Matoić", Position.PF, 198),
    igrac(18, "Ivan", "Mileković", Position.PG, 186),
    igrac(19, "Florijan", "Šašek", Position.C, 201),
    igrac(20, "Ivan", "Svoboda", Position.C, 206),
    igrac(21, "Filippo", "Valenti", Position.SG, 193),
  ]),
  sastav("Varaždin", "Varaždin", [
    igrac(3, "Fran", "Dolenc", Position.PG, 185),
    igrac(4, "Jan", "Babić", Position.SG, 187),
    igrac(5, "Andrej", "Martinez", Position.PG, 182),
    igrac(6, "Kruno", "Smontara", Position.SG, 191),
    igrac(7, "Ruben", "Brezovec", Position.C, 210),
    igrac(8, "Frane", "Ahmetović", Position.SF, 195),
    igrac(9, "Matej", "Mikulić", Position.SG, 188),
    igrac(10, "Jan", "Grđan", Position.SF, 195),
    igrac(11, "Andro", "Pešić", Position.SF, 197),
    igrac(12, "Roko", "Čović", Position.PF, 199),
    igrac(13, "Rion", "Jetishi", Position.SF, 193),
    igrac(14, "Lovro", "Ivanković", Position.C, 204),
    igrac(15, "Patrik", "Ostoja", Position.PF, 201),
    igrac(17, "Mihael", "Starčević", Position.PF, 198),
    igrac(18, "Lovro", "Štiber", Position.PG, 181),
    igrac(19, "Andro", "Svaty", Position.SG, 186),
    igrac(20, "Niko", "Terek", Position.PG, 187),
    igrac(21, "Matija", "Belošević", Position.PF, 198),
    igrac(22, "Lovro", "Vrhoci", Position.C, 209),
    igrac(44, "Franko", "Miko", Position.C, 202),
  ]),
  sastav("Vedi", null, [
    igrac(4, "Bruno", "Anušić", Position.PG, 184),
    igrac(5, "Roman", "Čimbur", Position.PF, 200),
    igrac(6, "Leo", "Čizmić", Position.PG, 183),
    igrac(7, "Matija", "Crnoja", Position.SF, 194),
    igrac(8, "Niko", "Gavranović", Position.PG, 180),
    igrac(9, "Krešimir", "Grgić", Position.PF, 202),
    igrac(10, "Mateo", "Hunjek", Position.SF, 192),
    igrac(11, "Dean", "Krajinović", Position.C, 210),
    igrac(12, "Deni", "Krajinović", Position.SF, 195),
    igrac(13, "Ivan", "Laić", Position.SG, 186),
    igrac(14, "Ante", "Mamić", Position.SG, 192),
    igrac(15, "Petar", "Marušić", Position.PG, 181),
    igrac(17, "Leon", "Mudri", Position.SF, 196),
    igrac(18, "Luka", "Palac", Position.C, 208),
    igrac(19, "Karlo", "Pandur", Position.SG, 188),
    igrac(20, "Ivan", "Sabljić", Position.C, 208),
    igrac(21, "Josip", "Stepančić Pribil", Position.PF, 197),
    igrac(22, "Ivan", "Stjepanović", Position.PF, 200),
    igrac(23, "Jan Zvonimir", "Vrdoljak", Position.C, 204),
    igrac(24, "Julijan", "Zadravec", Position.PG, 186),
    igrac(25, "Stefan", "Zadravec", Position.SG, 186),
  ]),
  sastav("Virka", null, [
    igrac(4, "Dominik", "Davidović", Position.SG, 189),
    igrac(5, "Marin", "Ferenčević", Position.PG, 182),
    igrac(6, "Petar", "Fuis", Position.SG, 186),
    igrac(7, "Jakov", "Jurlina", Position.SF, 195),
    igrac(8, "Nikola", "Krstanović", Position.C, 210),
    igrac(9, "Siniša", "Mihajlović", Position.PG, 186),
    igrac(10, "Antonio", "Pavlović", Position.C, 208),
    igrac(11, "Damjan", "Pažin", Position.PG, 184),
    igrac(12, "Sven", "Petrović", Position.PF, 202),
    igrac(13, "Zvonimir", "Petrović", Position.PF, 198),
    igrac(14, "Roko", "Rendulić", Position.PG, 184),
    igrac(15, "Mislav", "Škvarić", Position.PF, 204),
    igrac(17, "Josip", "Šutalo", Position.SF, 193),
    igrac(18, "Marko", "Teskera", Position.C, 205),
    igrac(19, "Emanuel", "Vidović", Position.SF, 198),
    igrac(20, "Marko", "Vrekić", Position.SG, 187),
  ]),
];
