import { EventType, SubstitutionDirection } from "@ibozak23/kosarkaska-analitika";

export type Strana = "HOME" | "AWAY";

interface OsnovaDemonstracijskogDogadjaja {
  readonly strana: Strana;
  readonly jerseyNumber: number;
  readonly quarter: number;
  readonly minute: number;
  readonly second: number;
}

export interface DemonstracijskiSut extends OsnovaDemonstracijskogDogadjaja {
  readonly type: EventType.SHOT;
  readonly points: 1 | 2 | 3;
  readonly made: boolean;
}

export interface DemonstracijskaIzmjena extends OsnovaDemonstracijskogDogadjaja {
  readonly type: EventType.SUBSTITUTION;
  readonly direction: SubstitutionDirection;
}

export interface JednostavniDemonstracijskiDogadjaj extends OsnovaDemonstracijskogDogadjaja {
  readonly type: Exclude<EventType, EventType.SHOT | EventType.SUBSTITUTION>;
}

export type DemonstracijskiDogadjaj = DemonstracijskiSut | DemonstracijskaIzmjena | JednostavniDemonstracijskiDogadjaj;

const DOMACI: Strana = "HOME";
const GOSTI: Strana = "AWAY";

function jednostavniDogadjaj(
  strana: Strana,
  jerseyNumber: number,
  quarter: number,
  minute: number,
  second: number,
  type: Exclude<EventType, EventType.SHOT | EventType.SUBSTITUTION>
): JednostavniDemonstracijskiDogadjaj {
  return { strana, jerseyNumber, quarter, minute, second, type };
}

function sut(
  strana: Strana,
  jerseyNumber: number,
  quarter: number,
  minute: number,
  second: number,
  points: 1 | 2 | 3,
  made: boolean
): DemonstracijskiSut {
  return { strana, jerseyNumber, quarter, minute, second, type: EventType.SHOT, points, made };
}

function izmjena(
  strana: Strana,
  jerseyNumber: number,
  quarter: number,
  minute: number,
  second: number,
  direction: SubstitutionDirection
): DemonstracijskaIzmjena {
  return { strana, jerseyNumber, quarter, minute, second, type: EventType.SUBSTITUTION, direction };
}

export const IME_DOMACEG_TIMA = "Ivančica";
export const IME_GOSTUJUCEG_TIMA = "Varaždin";

export const DRESOVI_DOMACE_PETORKE: readonly number[] = [4, 7, 9, 11, 13];
export const DRESOVI_GOSTUJUCE_PETORKE: readonly number[] = [3, 6, 8, 12, 14];

export const VRIJEME_UTAKMICE = new Date("2025-11-15T19:00:00+01:00");

export const DOGADJAJI_UTAKMICE: readonly DemonstracijskiDogadjaj[] = [
  jednostavniDogadjaj(DOMACI, 4, 1, 9, 51, EventType.ASSIST),
  sut(DOMACI, 7, 1, 9, 51, 3, true),
  jednostavniDogadjaj(GOSTI, 3, 1, 9, 34, EventType.ASSIST),
  sut(GOSTI, 6, 1, 9, 34, 2, true),
  sut(DOMACI, 13, 1, 9, 20, 2, true),
  jednostavniDogadjaj(DOMACI, 11, 1, 9, 11, EventType.FOUL),
  sut(GOSTI, 6, 1, 9, 4, 3, true),
  sut(DOMACI, 9, 1, 8, 47, 2, true),
  sut(GOSTI, 6, 1, 8, 30, 2, true),
  sut(DOMACI, 7, 1, 8, 18, 2, false),
  jednostavniDogadjaj(GOSTI, 14, 1, 8, 18, EventType.BLOCK),
  jednostavniDogadjaj(DOMACI, 13, 1, 8, 17, EventType.REBOUND_OFF),
  jednostavniDogadjaj(DOMACI, 4, 1, 8, 14, EventType.ASSIST),
  sut(DOMACI, 7, 1, 8, 14, 3, true),
  sut(GOSTI, 6, 1, 8, 0, 3, false),
  jednostavniDogadjaj(DOMACI, 13, 1, 7, 59, EventType.REBOUND_DEF),
  sut(DOMACI, 11, 1, 7, 44, 2, true),
  jednostavniDogadjaj(DOMACI, 9, 1, 7, 34, EventType.FOUL),
  sut(GOSTI, 6, 1, 7, 31, 3, false),
  jednostavniDogadjaj(GOSTI, 14, 1, 7, 30, EventType.REBOUND_OFF),
  jednostavniDogadjaj(GOSTI, 8, 1, 7, 26, EventType.ASSIST),
  sut(GOSTI, 6, 1, 7, 26, 2, true),
  jednostavniDogadjaj(GOSTI, 12, 1, 7, 10, EventType.FOUL),
  sut(DOMACI, 13, 1, 7, 8, 1, false),
  sut(DOMACI, 13, 1, 7, 6, 1, true),
  sut(GOSTI, 6, 1, 6, 53, 2, false),
  jednostavniDogadjaj(DOMACI, 13, 1, 6, 52, EventType.REBOUND_DEF),
  sut(DOMACI, 13, 1, 6, 38, 2, true),
  sut(GOSTI, 8, 1, 6, 25, 2, false),
  jednostavniDogadjaj(GOSTI, 12, 1, 6, 24, EventType.REBOUND_OFF),
  jednostavniDogadjaj(GOSTI, 6, 1, 6, 20, EventType.ASSIST),
  sut(GOSTI, 8, 1, 6, 20, 3, true),
  jednostavniDogadjaj(DOMACI, 7, 1, 6, 7, EventType.ASSIST),
  sut(DOMACI, 9, 1, 6, 7, 2, true),
  sut(GOSTI, 6, 1, 5, 49, 3, false),
  jednostavniDogadjaj(DOMACI, 11, 1, 5, 48, EventType.REBOUND_DEF),
  jednostavniDogadjaj(GOSTI, 14, 1, 5, 37, EventType.FOUL),
  izmjena(GOSTI, 3, 1, 5, 36, SubstitutionDirection.OUT),
  izmjena(GOSTI, 12, 1, 5, 36, SubstitutionDirection.OUT),
  izmjena(GOSTI, 5, 1, 5, 36, SubstitutionDirection.IN),
  izmjena(GOSTI, 21, 1, 5, 36, SubstitutionDirection.IN),
  sut(DOMACI, 7, 1, 5, 31, 2, false),
  jednostavniDogadjaj(GOSTI, 8, 1, 5, 31, EventType.BLOCK),
  jednostavniDogadjaj(GOSTI, 14, 1, 5, 30, EventType.REBOUND_DEF),
  jednostavniDogadjaj(DOMACI, 11, 1, 5, 21, EventType.FOUL),
  jednostavniDogadjaj(GOSTI, 5, 1, 5, 16, EventType.ASSIST),
  sut(GOSTI, 6, 1, 5, 16, 3, true),
  izmjena(DOMACI, 4, 1, 5, 12, SubstitutionDirection.OUT),
  izmjena(DOMACI, 11, 1, 5, 12, SubstitutionDirection.OUT),
  izmjena(DOMACI, 5, 1, 5, 12, SubstitutionDirection.IN),
  izmjena(DOMACI, 12, 1, 5, 12, SubstitutionDirection.IN),
  jednostavniDogadjaj(GOSTI, 21, 1, 5, 6, EventType.FOUL),
  jednostavniDogadjaj(DOMACI, 5, 1, 4, 59, EventType.ASSIST),
  sut(DOMACI, 12, 1, 4, 59, 2, true),
  sut(GOSTI, 21, 1, 4, 44, 2, false),
  jednostavniDogadjaj(DOMACI, 12, 1, 4, 43, EventType.REBOUND_DEF),
  sut(DOMACI, 5, 1, 4, 29, 2, false),
  jednostavniDogadjaj(GOSTI, 14, 1, 4, 28, EventType.REBOUND_DEF),
  jednostavniDogadjaj(DOMACI, 12, 1, 4, 13, EventType.FOUL),
  sut(GOSTI, 6, 1, 4, 11, 1, true),
  sut(GOSTI, 6, 1, 4, 9, 1, true),
  jednostavniDogadjaj(GOSTI, 21, 1, 3, 57, EventType.FOUL),
  sut(DOMACI, 12, 1, 3, 55, 1, true),
  sut(DOMACI, 12, 1, 3, 53, 1, true),
  sut(GOSTI, 21, 1, 3, 40, 2, true),
  sut(DOMACI, 7, 1, 3, 26, 3, false),
  jednostavniDogadjaj(DOMACI, 12, 1, 3, 25, EventType.REBOUND_OFF),
  sut(DOMACI, 12, 1, 3, 20, 2, true),
  jednostavniDogadjaj(DOMACI, 12, 1, 3, 12, EventType.FOUL),
  sut(GOSTI, 5, 1, 3, 5, 3, false),
  jednostavniDogadjaj(DOMACI, 13, 1, 3, 4, EventType.REBOUND_DEF),
  jednostavniDogadjaj(GOSTI, 5, 1, 2, 54, EventType.FOUL),
  sut(DOMACI, 5, 1, 2, 48, 3, false),
  jednostavniDogadjaj(GOSTI, 8, 1, 2, 47, EventType.REBOUND_DEF),
  jednostavniDogadjaj(GOSTI, 8, 1, 2, 33, EventType.ASSIST),
  sut(GOSTI, 5, 1, 2, 33, 2, true),
  sut(DOMACI, 7, 1, 2, 19, 3, true),
  sut(GOSTI, 8, 1, 2, 4, 3, false),
  jednostavniDogadjaj(DOMACI, 9, 1, 2, 3, EventType.REBOUND_DEF),
  jednostavniDogadjaj(GOSTI, 8, 1, 1, 52, EventType.FOUL),
  sut(DOMACI, 7, 1, 1, 46, 3, false),
  jednostavniDogadjaj(GOSTI, 21, 1, 1, 45, EventType.REBOUND_DEF),
  jednostavniDogadjaj(DOMACI, 5, 1, 1, 35, EventType.FOUL),
  sut(GOSTI, 14, 1, 1, 28, 2, true),
  sut(DOMACI, 5, 1, 1, 12, 3, true),
  sut(GOSTI, 6, 1, 0, 58, 3, false),
  jednostavniDogadjaj(DOMACI, 5, 1, 0, 57, EventType.REBOUND_DEF),
  sut(DOMACI, 9, 1, 0, 41, 3, false),
  jednostavniDogadjaj(GOSTI, 14, 1, 0, 40, EventType.REBOUND_DEF),
  jednostavniDogadjaj(DOMACI, 13, 1, 0, 24, EventType.FOUL),
  sut(GOSTI, 8, 1, 0, 22, 1, true),
  sut(GOSTI, 8, 1, 0, 20, 1, true),
  jednostavniDogadjaj(GOSTI, 6, 1, 0, 8, EventType.FOUL),
  sut(DOMACI, 9, 1, 0, 6, 1, true),
  sut(DOMACI, 9, 1, 0, 4, 1, true),
  izmjena(DOMACI, 5, 2, 10, 0, SubstitutionDirection.OUT),
  izmjena(DOMACI, 9, 2, 10, 0, SubstitutionDirection.OUT),
  izmjena(DOMACI, 13, 2, 10, 0, SubstitutionDirection.OUT),
  izmjena(GOSTI, 5, 2, 10, 0, SubstitutionDirection.OUT),
  izmjena(GOSTI, 8, 2, 10, 0, SubstitutionDirection.OUT),
  izmjena(GOSTI, 21, 2, 10, 0, SubstitutionDirection.OUT),
  izmjena(GOSTI, 14, 2, 10, 0, SubstitutionDirection.OUT),
  izmjena(DOMACI, 4, 2, 10, 0, SubstitutionDirection.IN),
  izmjena(DOMACI, 10, 2, 10, 0, SubstitutionDirection.IN),
  izmjena(DOMACI, 15, 2, 10, 0, SubstitutionDirection.IN),
  izmjena(GOSTI, 3, 2, 10, 0, SubstitutionDirection.IN),
  izmjena(GOSTI, 11, 2, 10, 0, SubstitutionDirection.IN),
  izmjena(GOSTI, 12, 2, 10, 0, SubstitutionDirection.IN),
  izmjena(GOSTI, 44, 2, 10, 0, SubstitutionDirection.IN),
  jednostavniDogadjaj(GOSTI, 3, 2, 9, 53, EventType.ASSIST),
  sut(GOSTI, 11, 2, 9, 53, 3, true),
  jednostavniDogadjaj(DOMACI, 7, 2, 9, 39, EventType.ASSIST),
  sut(DOMACI, 12, 2, 9, 39, 2, true),
  jednostavniDogadjaj(DOMACI, 15, 2, 9, 28, EventType.FOUL),
  sut(GOSTI, 11, 2, 9, 21, 2, false),
  jednostavniDogadjaj(DOMACI, 15, 2, 9, 20, EventType.REBOUND_DEF),
  sut(DOMACI, 12, 2, 9, 3, 2, false),
  jednostavniDogadjaj(GOSTI, 44, 2, 9, 2, EventType.REBOUND_DEF),
  jednostavniDogadjaj(GOSTI, 6, 2, 8, 47, EventType.TURNOVER),
  jednostavniDogadjaj(DOMACI, 12, 2, 8, 30, EventType.ASSIST),
  sut(DOMACI, 10, 2, 8, 30, 2, true),
  sut(GOSTI, 11, 2, 8, 16, 3, false),
  jednostavniDogadjaj(GOSTI, 44, 2, 8, 15, EventType.REBOUND_OFF),
  jednostavniDogadjaj(GOSTI, 6, 2, 8, 11, EventType.ASSIST),
  sut(GOSTI, 11, 2, 8, 11, 2, true),
  sut(DOMACI, 10, 2, 7, 57, 3, false),
  jednostavniDogadjaj(GOSTI, 12, 2, 7, 56, EventType.REBOUND_DEF),
  jednostavniDogadjaj(DOMACI, 12, 2, 7, 46, EventType.FOUL),
  sut(GOSTI, 11, 2, 7, 42, 2, false),
  jednostavniDogadjaj(DOMACI, 7, 2, 7, 41, EventType.REBOUND_DEF),
  jednostavniDogadjaj(DOMACI, 12, 2, 7, 28, EventType.TURNOVER),
  jednostavniDogadjaj(GOSTI, 6, 2, 7, 28, EventType.STEAL),
  jednostavniDogadjaj(GOSTI, 11, 2, 7, 11, EventType.TURNOVER),
  sut(DOMACI, 15, 2, 6, 53, 2, true),
  jednostavniDogadjaj(GOSTI, 11, 2, 6, 36, EventType.ASSIST),
  sut(GOSTI, 44, 2, 6, 36, 2, true),
  sut(DOMACI, 7, 2, 6, 23, 3, false),
  jednostavniDogadjaj(DOMACI, 12, 2, 6, 22, EventType.REBOUND_OFF),
  sut(DOMACI, 7, 2, 6, 18, 3, false),
  jednostavniDogadjaj(GOSTI, 11, 2, 6, 17, EventType.REBOUND_DEF),
  sut(GOSTI, 6, 2, 6, 8, 3, false),
  jednostavniDogadjaj(GOSTI, 11, 2, 6, 7, EventType.REBOUND_OFF),
  sut(GOSTI, 44, 2, 6, 3, 2, false),
  jednostavniDogadjaj(DOMACI, 12, 2, 6, 2, EventType.REBOUND_DEF),
  jednostavniDogadjaj(DOMACI, 15, 2, 5, 50, EventType.TURNOVER),
  jednostavniDogadjaj(GOSTI, 11, 2, 5, 50, EventType.STEAL),
  izmjena(GOSTI, 11, 2, 5, 42, SubstitutionDirection.OUT),
  izmjena(GOSTI, 44, 2, 5, 42, SubstitutionDirection.OUT),
  izmjena(GOSTI, 8, 2, 5, 42, SubstitutionDirection.IN),
  izmjena(GOSTI, 14, 2, 5, 42, SubstitutionDirection.IN),
  jednostavniDogadjaj(GOSTI, 6, 2, 5, 34, EventType.TURNOVER),
  jednostavniDogadjaj(DOMACI, 7, 2, 5, 34, EventType.STEAL),
  jednostavniDogadjaj(GOSTI, 14, 2, 5, 18, EventType.FOUL),
  sut(DOMACI, 7, 2, 5, 16, 1, true),
  sut(DOMACI, 7, 2, 5, 14, 1, true),
  jednostavniDogadjaj(DOMACI, 10, 2, 5, 0, EventType.FOUL),
  sut(GOSTI, 12, 2, 4, 58, 1, false),
  sut(GOSTI, 12, 2, 4, 56, 1, true),
  izmjena(DOMACI, 10, 2, 4, 48, SubstitutionDirection.OUT),
  izmjena(DOMACI, 12, 2, 4, 48, SubstitutionDirection.OUT),
  izmjena(DOMACI, 15, 2, 4, 48, SubstitutionDirection.OUT),
  izmjena(DOMACI, 9, 2, 4, 48, SubstitutionDirection.IN),
  izmjena(DOMACI, 11, 2, 4, 48, SubstitutionDirection.IN),
  izmjena(DOMACI, 13, 2, 4, 48, SubstitutionDirection.IN),
  jednostavniDogadjaj(DOMACI, 4, 2, 4, 44, EventType.ASSIST),
  sut(DOMACI, 7, 2, 4, 44, 3, true),
  sut(GOSTI, 12, 2, 4, 28, 2, true),
  sut(DOMACI, 4, 2, 4, 13, 3, false),
  jednostavniDogadjaj(GOSTI, 12, 2, 4, 12, EventType.REBOUND_DEF),
  sut(GOSTI, 8, 2, 4, 0, 2, false),
  jednostavniDogadjaj(GOSTI, 14, 2, 3, 59, EventType.REBOUND_OFF),
  sut(GOSTI, 12, 2, 3, 54, 2, false),
  jednostavniDogadjaj(DOMACI, 7, 2, 3, 53, EventType.REBOUND_DEF),
  jednostavniDogadjaj(GOSTI, 12, 2, 3, 46, EventType.FOUL),
  jednostavniDogadjaj(DOMACI, 7, 2, 3, 40, EventType.TURNOVER),
  jednostavniDogadjaj(GOSTI, 8, 2, 3, 24, EventType.TURNOVER),
  jednostavniDogadjaj(DOMACI, 7, 2, 3, 24, EventType.STEAL),
  jednostavniDogadjaj(DOMACI, 7, 2, 3, 9, EventType.ASSIST),
  sut(DOMACI, 9, 2, 3, 9, 2, true),
  jednostavniDogadjaj(DOMACI, 7, 2, 2, 58, EventType.FOUL),
  sut(GOSTI, 3, 2, 2, 54, 2, false),
  jednostavniDogadjaj(DOMACI, 13, 2, 2, 54, EventType.BLOCK),
  jednostavniDogadjaj(GOSTI, 6, 2, 2, 53, EventType.REBOUND_OFF),
  sut(GOSTI, 6, 2, 2, 48, 3, true),
  sut(DOMACI, 13, 2, 2, 35, 2, false),
  jednostavniDogadjaj(GOSTI, 6, 2, 2, 34, EventType.REBOUND_DEF),
  sut(GOSTI, 6, 2, 2, 20, 2, false),
  jednostavniDogadjaj(DOMACI, 9, 2, 2, 19, EventType.REBOUND_DEF),
  jednostavniDogadjaj(DOMACI, 9, 2, 2, 3, EventType.TURNOVER),
  jednostavniDogadjaj(GOSTI, 6, 2, 2, 3, EventType.STEAL),
  jednostavniDogadjaj(GOSTI, 14, 2, 1, 47, EventType.TURNOVER),
  jednostavniDogadjaj(DOMACI, 4, 2, 1, 47, EventType.STEAL),
  sut(DOMACI, 9, 2, 1, 34, 2, false),
  jednostavniDogadjaj(GOSTI, 14, 2, 1, 34, EventType.BLOCK),
  jednostavniDogadjaj(DOMACI, 9, 2, 1, 33, EventType.REBOUND_OFF),
  jednostavniDogadjaj(DOMACI, 9, 2, 1, 29, EventType.ASSIST),
  sut(DOMACI, 4, 2, 1, 29, 3, true),
  sut(GOSTI, 8, 2, 1, 14, 2, true),
  jednostavniDogadjaj(GOSTI, 3, 2, 1, 2, EventType.FOUL),
  sut(DOMACI, 11, 2, 0, 56, 3, false),
  jednostavniDogadjaj(GOSTI, 8, 2, 0, 55, EventType.REBOUND_DEF),
  jednostavniDogadjaj(DOMACI, 4, 2, 0, 46, EventType.FOUL),
  sut(GOSTI, 8, 2, 0, 41, 3, false),
  jednostavniDogadjaj(DOMACI, 13, 2, 0, 40, EventType.REBOUND_DEF),
  sut(DOMACI, 7, 2, 0, 29, 3, false),
  jednostavniDogadjaj(DOMACI, 13, 2, 0, 28, EventType.REBOUND_OFF),
  jednostavniDogadjaj(DOMACI, 4, 2, 0, 24, EventType.TURNOVER),
  jednostavniDogadjaj(GOSTI, 12, 2, 0, 8, EventType.TURNOVER),
  jednostavniDogadjaj(DOMACI, 9, 2, 0, 8, EventType.STEAL),
  izmjena(DOMACI, 7, 3, 10, 0, SubstitutionDirection.OUT),
  izmjena(GOSTI, 6, 3, 10, 0, SubstitutionDirection.OUT),
  izmjena(DOMACI, 8, 3, 10, 0, SubstitutionDirection.IN),
  izmjena(GOSTI, 9, 3, 10, 0, SubstitutionDirection.IN),
  jednostavniDogadjaj(GOSTI, 9, 3, 9, 51, EventType.FOUL),
  sut(DOMACI, 8, 3, 9, 49, 1, false),
  sut(DOMACI, 8, 3, 9, 47, 1, true),
  jednostavniDogadjaj(DOMACI, 8, 3, 9, 38, EventType.FOUL),
  sut(GOSTI, 14, 3, 9, 36, 1, true),
  sut(GOSTI, 14, 3, 9, 34, 1, true),
  sut(DOMACI, 8, 3, 9, 22, 2, true),
  jednostavniDogadjaj(GOSTI, 14, 3, 9, 5, EventType.ASSIST),
  sut(GOSTI, 9, 3, 9, 5, 2, true),
  sut(DOMACI, 8, 3, 8, 49, 3, false),
  jednostavniDogadjaj(GOSTI, 9, 3, 8, 48, EventType.REBOUND_DEF),
  sut(GOSTI, 9, 3, 8, 32, 2, false),
  jednostavniDogadjaj(DOMACI, 9, 3, 8, 32, EventType.BLOCK),
  jednostavniDogadjaj(DOMACI, 8, 3, 8, 31, EventType.REBOUND_DEF),
  jednostavniDogadjaj(DOMACI, 8, 3, 8, 13, EventType.TURNOVER),
  jednostavniDogadjaj(GOSTI, 3, 3, 7, 56, EventType.TURNOVER),
  jednostavniDogadjaj(DOMACI, 4, 3, 7, 41, EventType.ASSIST),
  sut(DOMACI, 8, 3, 7, 41, 3, true),
  jednostavniDogadjaj(GOSTI, 12, 3, 7, 28, EventType.ASSIST),
  sut(GOSTI, 9, 3, 7, 28, 3, true),
  sut(DOMACI, 8, 3, 7, 15, 2, false),
  jednostavniDogadjaj(DOMACI, 11, 3, 7, 14, EventType.REBOUND_OFF),
  sut(DOMACI, 8, 3, 7, 8, 3, false),
  jednostavniDogadjaj(GOSTI, 14, 3, 7, 7, EventType.REBOUND_DEF),
  sut(GOSTI, 9, 3, 6, 56, 3, false),
  jednostavniDogadjaj(GOSTI, 8, 3, 6, 55, EventType.REBOUND_OFF),
  sut(GOSTI, 9, 3, 6, 51, 3, false),
  jednostavniDogadjaj(DOMACI, 4, 3, 6, 50, EventType.REBOUND_DEF),
  jednostavniDogadjaj(GOSTI, 9, 3, 6, 43, EventType.FOUL),
  jednostavniDogadjaj(DOMACI, 13, 3, 6, 38, EventType.TURNOVER),
  jednostavniDogadjaj(GOSTI, 9, 3, 6, 22, EventType.TURNOVER),
  sut(DOMACI, 8, 3, 6, 6, 2, true),
  jednostavniDogadjaj(GOSTI, 9, 3, 5, 51, EventType.ASSIST),
  sut(GOSTI, 14, 3, 5, 51, 2, true),
  sut(DOMACI, 13, 3, 5, 36, 2, false),
  jednostavniDogadjaj(DOMACI, 8, 3, 5, 35, EventType.REBOUND_OFF),
  sut(DOMACI, 9, 3, 5, 29, 2, false),
  jednostavniDogadjaj(GOSTI, 9, 3, 5, 28, EventType.REBOUND_DEF),
  izmjena(DOMACI, 4, 3, 5, 24, SubstitutionDirection.OUT),
  izmjena(DOMACI, 9, 3, 5, 24, SubstitutionDirection.OUT),
  izmjena(DOMACI, 13, 3, 5, 24, SubstitutionDirection.OUT),
  izmjena(DOMACI, 5, 3, 5, 24, SubstitutionDirection.IN),
  izmjena(DOMACI, 10, 3, 5, 24, SubstitutionDirection.IN),
  izmjena(DOMACI, 15, 3, 5, 24, SubstitutionDirection.IN),
  jednostavniDogadjaj(DOMACI, 15, 3, 5, 20, EventType.FOUL),
  sut(GOSTI, 14, 3, 5, 19, 2, false),
  jednostavniDogadjaj(GOSTI, 14, 3, 5, 18, EventType.REBOUND_OFF),
  sut(GOSTI, 9, 3, 5, 15, 3, false),
  jednostavniDogadjaj(DOMACI, 11, 3, 5, 15, EventType.BLOCK),
  jednostavniDogadjaj(DOMACI, 10, 3, 5, 14, EventType.REBOUND_DEF),
  jednostavniDogadjaj(DOMACI, 5, 3, 5, 3, EventType.TURNOVER),
  jednostavniDogadjaj(GOSTI, 8, 3, 4, 46, EventType.TURNOVER),
  jednostavniDogadjaj(DOMACI, 5, 3, 4, 46, EventType.STEAL),
  jednostavniDogadjaj(GOSTI, 8, 3, 4, 30, EventType.FOUL),
  sut(DOMACI, 11, 3, 4, 28, 1, true),
  sut(DOMACI, 11, 3, 4, 26, 1, true),
  izmjena(GOSTI, 3, 3, 4, 18, SubstitutionDirection.OUT),
  izmjena(GOSTI, 8, 3, 4, 18, SubstitutionDirection.OUT),
  izmjena(GOSTI, 12, 3, 4, 18, SubstitutionDirection.OUT),
  izmjena(GOSTI, 5, 3, 4, 18, SubstitutionDirection.IN),
  izmjena(GOSTI, 11, 3, 4, 18, SubstitutionDirection.IN),
  izmjena(GOSTI, 21, 3, 4, 18, SubstitutionDirection.IN),
  jednostavniDogadjaj(DOMACI, 8, 3, 4, 13, EventType.FOUL),
  sut(GOSTI, 11, 3, 4, 11, 1, false),
  sut(GOSTI, 11, 3, 4, 9, 1, true),
  jednostavniDogadjaj(GOSTI, 11, 3, 4, 1, EventType.FOUL),
  sut(DOMACI, 8, 3, 3, 55, 3, true),
  sut(GOSTI, 9, 3, 3, 40, 3, true),
  sut(DOMACI, 5, 3, 3, 24, 3, false),
  jednostavniDogadjaj(GOSTI, 14, 3, 3, 23, EventType.REBOUND_DEF),
  sut(GOSTI, 5, 3, 3, 8, 2, false),
  jednostavniDogadjaj(DOMACI, 15, 3, 3, 7, EventType.REBOUND_DEF),
  sut(DOMACI, 8, 3, 2, 55, 2, false),
  jednostavniDogadjaj(DOMACI, 15, 3, 2, 54, EventType.REBOUND_OFF),
  jednostavniDogadjaj(DOMACI, 10, 3, 2, 50, EventType.TURNOVER),
  jednostavniDogadjaj(GOSTI, 5, 3, 2, 36, EventType.TURNOVER),
  jednostavniDogadjaj(GOSTI, 14, 3, 2, 25, EventType.FOUL),
  jednostavniDogadjaj(DOMACI, 8, 3, 2, 18, EventType.ASSIST),
  sut(DOMACI, 11, 3, 2, 18, 2, true),
  sut(GOSTI, 14, 3, 2, 1, 2, true),
  sut(DOMACI, 10, 3, 1, 48, 2, false),
  jednostavniDogadjaj(DOMACI, 11, 3, 1, 47, EventType.REBOUND_OFF),
  sut(DOMACI, 15, 3, 1, 42, 2, false),
  jednostavniDogadjaj(GOSTI, 11, 3, 1, 41, EventType.REBOUND_DEF),
  sut(GOSTI, 21, 3, 1, 30, 2, false),
  jednostavniDogadjaj(DOMACI, 8, 3, 1, 29, EventType.REBOUND_DEF),
  jednostavniDogadjaj(DOMACI, 8, 3, 1, 16, EventType.TURNOVER),
  jednostavniDogadjaj(DOMACI, 11, 3, 1, 6, EventType.FOUL),
  jednostavniDogadjaj(GOSTI, 21, 3, 0, 58, EventType.TURNOVER),
  jednostavniDogadjaj(DOMACI, 8, 3, 0, 58, EventType.STEAL),
  jednostavniDogadjaj(DOMACI, 8, 3, 0, 40, EventType.ASSIST),
  sut(DOMACI, 11, 3, 0, 40, 3, true),
  sut(GOSTI, 14, 3, 0, 28, 2, false),
  jednostavniDogadjaj(GOSTI, 21, 3, 0, 27, EventType.REBOUND_OFF),
  jednostavniDogadjaj(GOSTI, 9, 3, 0, 22, EventType.ASSIST),
  sut(GOSTI, 11, 3, 0, 22, 2, true),
  jednostavniDogadjaj(GOSTI, 11, 3, 0, 14, EventType.FOUL),
  jednostavniDogadjaj(DOMACI, 11, 3, 0, 10, EventType.TURNOVER),
  jednostavniDogadjaj(GOSTI, 9, 3, 0, 10, EventType.STEAL),
  izmjena(DOMACI, 5, 4, 10, 0, SubstitutionDirection.OUT),
  izmjena(DOMACI, 8, 4, 10, 0, SubstitutionDirection.OUT),
  izmjena(DOMACI, 10, 4, 10, 0, SubstitutionDirection.OUT),
  izmjena(DOMACI, 15, 4, 10, 0, SubstitutionDirection.OUT),
  izmjena(GOSTI, 5, 4, 10, 0, SubstitutionDirection.OUT),
  izmjena(GOSTI, 9, 4, 10, 0, SubstitutionDirection.OUT),
  izmjena(GOSTI, 11, 4, 10, 0, SubstitutionDirection.OUT),
  izmjena(GOSTI, 21, 4, 10, 0, SubstitutionDirection.OUT),
  izmjena(DOMACI, 4, 4, 10, 0, SubstitutionDirection.IN),
  izmjena(DOMACI, 7, 4, 10, 0, SubstitutionDirection.IN),
  izmjena(DOMACI, 9, 4, 10, 0, SubstitutionDirection.IN),
  izmjena(DOMACI, 13, 4, 10, 0, SubstitutionDirection.IN),
  izmjena(GOSTI, 3, 4, 10, 0, SubstitutionDirection.IN),
  izmjena(GOSTI, 6, 4, 10, 0, SubstitutionDirection.IN),
  izmjena(GOSTI, 8, 4, 10, 0, SubstitutionDirection.IN),
  izmjena(GOSTI, 12, 4, 10, 0, SubstitutionDirection.IN),
  sut(GOSTI, 8, 4, 9, 54, 3, false),
  jednostavniDogadjaj(DOMACI, 11, 4, 9, 53, EventType.REBOUND_DEF),
  jednostavniDogadjaj(GOSTI, 12, 4, 9, 42, EventType.FOUL),
  sut(DOMACI, 11, 4, 9, 37, 2, false),
  jednostavniDogadjaj(GOSTI, 12, 4, 9, 37, EventType.BLOCK),
  jednostavniDogadjaj(GOSTI, 8, 4, 9, 36, EventType.REBOUND_DEF),
  jednostavniDogadjaj(GOSTI, 14, 4, 9, 20, EventType.TURNOVER),
  jednostavniDogadjaj(GOSTI, 6, 4, 9, 4, EventType.FOUL),
  sut(DOMACI, 13, 4, 9, 2, 1, false),
  sut(DOMACI, 13, 4, 9, 0, 1, true),
  jednostavniDogadjaj(DOMACI, 9, 4, 8, 48, EventType.FOUL),
  sut(GOSTI, 12, 4, 8, 46, 1, false),
  sut(GOSTI, 12, 4, 8, 44, 1, true),
  jednostavniDogadjaj(GOSTI, 3, 4, 8, 37, EventType.FOUL),
  jednostavniDogadjaj(DOMACI, 11, 4, 8, 33, EventType.ASSIST),
  sut(DOMACI, 13, 4, 8, 33, 2, true),
  jednostavniDogadjaj(DOMACI, 13, 4, 8, 24, EventType.FOUL),
  sut(GOSTI, 8, 4, 8, 15, 3, true),
  sut(DOMACI, 11, 4, 7, 56, 2, false),
  jednostavniDogadjaj(GOSTI, 12, 4, 7, 55, EventType.REBOUND_DEF),
  sut(GOSTI, 12, 4, 7, 40, 3, false),
  jednostavniDogadjaj(DOMACI, 11, 4, 7, 39, EventType.REBOUND_DEF),
  sut(DOMACI, 4, 4, 7, 27, 3, false),
  jednostavniDogadjaj(DOMACI, 9, 4, 7, 26, EventType.REBOUND_OFF),
  jednostavniDogadjaj(DOMACI, 11, 4, 7, 21, EventType.TURNOVER),
  jednostavniDogadjaj(DOMACI, 7, 4, 7, 13, EventType.FOUL),
  jednostavniDogadjaj(GOSTI, 12, 4, 7, 9, EventType.TURNOVER),
  jednostavniDogadjaj(DOMACI, 11, 4, 7, 9, EventType.STEAL),
  sut(DOMACI, 13, 4, 6, 55, 2, true),
  jednostavniDogadjaj(GOSTI, 3, 4, 6, 37, EventType.ASSIST),
  sut(GOSTI, 12, 4, 6, 37, 2, true),
  sut(DOMACI, 9, 4, 6, 20, 3, false),
  jednostavniDogadjaj(GOSTI, 6, 4, 6, 19, EventType.REBOUND_DEF),
  sut(GOSTI, 3, 4, 6, 5, 3, false),
  jednostavniDogadjaj(DOMACI, 7, 4, 6, 4, EventType.REBOUND_DEF),
  sut(DOMACI, 13, 4, 5, 52, 2, false),
  jednostavniDogadjaj(DOMACI, 13, 4, 5, 51, EventType.REBOUND_OFF),
  jednostavniDogadjaj(DOMACI, 4, 4, 5, 46, EventType.TURNOVER),
  jednostavniDogadjaj(GOSTI, 8, 4, 5, 46, EventType.STEAL),
  sut(GOSTI, 6, 4, 5, 34, 2, false),
  jednostavniDogadjaj(GOSTI, 12, 4, 5, 33, EventType.REBOUND_OFF),
  jednostavniDogadjaj(GOSTI, 6, 4, 5, 29, EventType.TURNOVER),
  izmjena(GOSTI, 8, 4, 5, 24, SubstitutionDirection.OUT),
  izmjena(GOSTI, 14, 4, 5, 24, SubstitutionDirection.OUT),
  izmjena(GOSTI, 11, 4, 5, 24, SubstitutionDirection.IN),
  izmjena(GOSTI, 44, 4, 5, 24, SubstitutionDirection.IN),
  jednostavniDogadjaj(GOSTI, 44, 4, 5, 22, EventType.FOUL),
  jednostavniDogadjaj(DOMACI, 9, 4, 5, 17, EventType.ASSIST),
  sut(DOMACI, 7, 4, 5, 17, 2, true),
  sut(GOSTI, 3, 4, 5, 2, 3, true),
  sut(DOMACI, 4, 4, 4, 44, 2, false),
  jednostavniDogadjaj(GOSTI, 44, 4, 4, 44, EventType.BLOCK),
  jednostavniDogadjaj(GOSTI, 12, 4, 4, 43, EventType.REBOUND_DEF),
  izmjena(DOMACI, 11, 4, 4, 36, SubstitutionDirection.OUT),
  izmjena(DOMACI, 12, 4, 4, 36, SubstitutionDirection.IN),
  sut(GOSTI, 11, 4, 4, 26, 3, false),
  jednostavniDogadjaj(DOMACI, 4, 4, 4, 25, EventType.REBOUND_DEF),
  jednostavniDogadjaj(DOMACI, 7, 4, 4, 12, EventType.TURNOVER),
  jednostavniDogadjaj(GOSTI, 3, 4, 3, 58, EventType.TURNOVER),
  jednostavniDogadjaj(GOSTI, 44, 4, 3, 41, EventType.FOUL),
  sut(DOMACI, 4, 4, 3, 39, 1, false),
  sut(DOMACI, 4, 4, 3, 37, 1, true),
  jednostavniDogadjaj(DOMACI, 4, 4, 3, 24, EventType.FOUL),
  sut(GOSTI, 6, 4, 3, 22, 1, false),
  sut(GOSTI, 6, 4, 3, 20, 1, true),
  jednostavniDogadjaj(DOMACI, 13, 4, 3, 7, EventType.ASSIST),
  sut(DOMACI, 9, 4, 3, 7, 3, true),
  sut(GOSTI, 6, 4, 2, 51, 2, true),
  sut(DOMACI, 12, 4, 2, 34, 2, false),
  jednostavniDogadjaj(GOSTI, 44, 4, 2, 33, EventType.REBOUND_DEF),
  jednostavniDogadjaj(DOMACI, 9, 4, 2, 23, EventType.FOUL),
  sut(GOSTI, 3, 4, 2, 18, 3, false),
  jednostavniDogadjaj(DOMACI, 9, 4, 2, 17, EventType.REBOUND_DEF),
  jednostavniDogadjaj(DOMACI, 13, 4, 2, 3, EventType.TURNOVER),
  jednostavniDogadjaj(GOSTI, 44, 4, 1, 47, EventType.TURNOVER),
  sut(DOMACI, 4, 4, 1, 29, 2, true),
  jednostavniDogadjaj(GOSTI, 11, 4, 1, 12, EventType.ASSIST),
  sut(GOSTI, 12, 4, 1, 12, 2, true),
  sut(DOMACI, 7, 4, 0, 57, 3, false),
  jednostavniDogadjaj(GOSTI, 3, 4, 0, 56, EventType.REBOUND_DEF),
  sut(GOSTI, 12, 4, 0, 42, 2, false),
  jednostavniDogadjaj(DOMACI, 13, 4, 0, 41, EventType.REBOUND_DEF),
  jednostavniDogadjaj(DOMACI, 9, 4, 0, 24, EventType.TURNOVER),
  jednostavniDogadjaj(GOSTI, 3, 4, 0, 24, EventType.STEAL),
  jednostavniDogadjaj(GOSTI, 11, 4, 0, 7, EventType.TURNOVER),
];
